name: Deploy Flask App to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Copy Flask App to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app/app.py"
        target: "/home/ec2-user/app/app/"

    - name: Copy bash script to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app/get_ip.sh"
        target: "/home/ec2-user/app/app/"

    - name: SSH and Run Flask
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Matando procesos previos"
          pkill -f app.py || true
      
          echo "Iniciando Flask en segundo plano"
          chmod +x /home/ec2-user/app/app/app/get_ip.sh
          nohup python3 /home/ec2-user/app/app/app/app.py > /home/ec2-user/flask.log 2>&1 &
      
          sleep 3
      
          echo "Verificando si el proceso Flask está activo"
          pgrep -f app.py || (echo "❌ Flask no se está ejecutando" && exit 1)
      
          echo "✅ Flask se inició correctamente"
